[package]
name = "tuser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "tuser"

[dependencies]
actix-web = "^3.3.2"
actix-files = "^0.5.0"
derive_more = "^0.99.9"
thiserror = "^1.0"
async-trait = "0.1.52"
structopt = { version = "^0.3" }
uuid = { version = "^1.0.0-alpha.1", features = ["v4"] }
async-std = "^1.10.0"
serde = "1"
chrono = { version = "^0.4.19", features = ["serde"] }
serde_json = "1"
log = "^0.4.14"
url = "2.2.2"
simple-logging = { version = "^2.0.2" }