[package]
name = "rustus"
version = "0.1.0"
edition = "2021"
description = "TUS protocol implementation written in Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "rustus"

[dependencies]
actix-web = "^3.3.2"
actix-files = "^0.5.0"
derive_more = { version = "^0.99.9", default-features = false, features = ["display", "from", "from_str"] }
thiserror = "^1.0"
async-trait = "0.1.52"
structopt = { version = "^0.3" }
uuid = { version = "^1.0.0-alpha.1", features = ["v4"] }
async-std = "^1.10.0"
serde = "1"
chrono = { version = "^0.4.19", features = ["serde"] }
serde_json = "1"
log = "^0.4.14"
url = "2.2.2"
base64 = "^0.13.0"
simple-logging = { version = "^2.0.2" }
strfmt = "^0.1.6"
strum = { version = "0.23", features = ["derive"] }
rbson = { version = "2.0", optional = true }
rbatis = { version = "^3.0", default-features = false, features = ["runtime-async-std-rustls", "all-database"], optional = true }
mobc-redis = { version = "0.7.0", features = ["async-std-comp"], optional = true }


[features]
default = []
all = ["redis_info_storage", "db_info_storage"]
redis_info_storage = ["mobc-redis"]
db_info_storage = ["rbatis", "rbson"]