on:
  push:
    tags-ignore:
      - '**'

name: Lint check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -p rustus -- -W clippy::all -W clippy::pedantic -D warnings
  fmt_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cargo fmt -- --check